# Generated by Django 4.1.3 on 2022-12-12 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webify', '0003_alter_useraccount_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='default',
            field=models.BooleanField(default=False),
        ),
    ]
