# Generated by Django 4.1.3 on 2022-12-12 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webify', '0004_useraccount_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='acc_type',
            field=models.CharField(choices=[('income', 'Income'), ('expense', 'Expense'), ('investment', 'Investment')], default='expense', max_length=400),
        ),
    ]
