# Generated by Django 4.1.3 on 2022-12-13 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webify', '0005_useraccount_acc_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='userwallet',
            name='wallet_id',
            field=models.CharField(default='0', max_length=7),
        ),
    ]
