# Generated by Django 4.1.3 on 2022-12-16 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webify', '0006_userwallet_wallet_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='payhistory',
            name='date_created',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='payhistory',
            name='reason_type',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
        migrations.AddField(
            model_name='payhistory',
            name='status',
            field=models.CharField(blank=True, default='', max_length=15),
        ),
    ]
