# Generated by Django 4.1.3 on 2022-12-16 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webify', '0007_payhistory_date_created_payhistory_reason_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payhistory',
            name='reason',
            field=models.TextField(blank=True, default='', max_length=500),
        ),
    ]
