# Generated by Django 4.1.3 on 2023-01-01 22:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Form1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('company', 'Company'), ('individual', 'Individual')], default='company', max_length=400)),
                ('website_type', models.CharField(blank=True, max_length=100, null=True)),
                ('finder_code', models.CharField(blank=True, max_length=5, null=True)),
                ('creation_mode', models.CharField(choices=[('company', 'Company'), ('individual', 'Individual')], default='developer', max_length=400)),
                ('project_name', models.CharField(blank=True, max_length=100, null=True)),
                ('website_example', models.CharField(blank=True, max_length=100, null=True)),
                ('db_space', models.CharField(blank=True, max_length=100, null=True)),
                ('logo', models.ImageField(upload_to='')),
                ('mobile_whatsapp_line', models.CharField(blank=True, max_length=100, null=True)),
                ('language_name', models.CharField(blank=True, max_length=100, null=True)),
                ('compeny_name', models.CharField(blank=True, max_length=100, null=True)),
                ('compeny_type', models.CharField(blank=True, max_length=100, null=True)),
                ('template_name', models.CharField(blank=True, max_length=100, null=True)),
                ('demo', models.BooleanField(default=False)),
                ('system', models.CharField(blank=True, max_length=100, null=True)),
                ('facebook', models.CharField(blank=True, max_length=100, null=True)),
                ('instagram', models.CharField(blank=True, max_length=100, null=True)),
                ('tweeter', models.CharField(blank=True, max_length=100, null=True)),
                ('gmail', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(blank=True, max_length=100, null=True)),
                ('your_hosting', models.CharField(blank=True, max_length=100, null=True)),
                ('username', models.CharField(blank=True, max_length=100, null=True)),
                ('password', models.CharField(blank=True, max_length=100, null=True)),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('domain_name', models.CharField(blank=True, max_length=100, null=True)),
                ('need_team', models.BooleanField(default=False)),
                ('fax_line', models.CharField(blank=True, max_length=100, null=True)),
                ('map_address', models.CharField(blank=True, max_length=100, null=True)),
                ('linkedin', models.CharField(blank=True, max_length=100, null=True)),
                ('web_color', models.CharField(blank=True, max_length=100, null=True)),
                ('creating_for', models.CharField(blank=True, max_length=100, null=True)),
                ('compeny_address', models.CharField(blank=True, max_length=100, null=True)),
                ('language', models.CharField(blank=True, max_length=100, null=True)),
                ('need_tutorial', models.CharField(blank=True, max_length=100, null=True)),
                ('cvv', models.CharField(blank=True, max_length=100, null=True)),
                ('card_number', models.CharField(blank=True, max_length=100, null=True)),
                ('card_name', models.CharField(blank=True, max_length=100, null=True)),
                ('expire_date', models.CharField(blank=True, max_length=100, null=True)),
                ('card_type', models.CharField(blank=True, max_length=100, null=True)),
                ('ssl_cert', models.BooleanField(default=False)),
                ('server_hostname', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('country_code', models.CharField(blank=True, max_length=100, null=True)),
                ('num_of_staff', models.IntegerField(blank=True, null=True)),
                ('private_email', models.CharField(blank=True, max_length=3, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Futures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('Image', models.ImageField(upload_to='media/dashboard')),
                ('discription', models.TextField(max_length=90)),
                ('tag', models.CharField(max_length=100)),
                ('item_created_date', models.DateTimeField(auto_now=True)),
                ('item_updated_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PayHistoryForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paystack_charge_id', models.CharField(blank=True, default='', max_length=100)),
                ('paystack_access_code', models.CharField(blank=True, default='', max_length=100)),
                ('payment_for', models.CharField(choices=[('domain', 'Domain'), ('hosting', 'Hosting'), ('ssl', 'SSL'), ('pmail', 'Pmail'), ('fsd', 'FSD'), ('maintainers', 'Maintainers'), ('orders', 'Orders')], default='orders', max_length=400)),
                ('status', models.CharField(choices=[('awaiting', 'Awaiting'), ('declind', 'Declind'), ('confirmed', 'Confirmed')], default='awaiting', max_length=400)),
                ('paid', models.BooleanField(default=False)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Form4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template', models.CharField(blank=True, max_length=100, null=True)),
                ('your_template', models.FileField(blank=True, null=True, upload_to='')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Form3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('futures', models.ManyToManyField(to='Dashbord.futures')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Form2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finder_code', models.CharField(blank=True, max_length=5, null=True)),
                ('html', models.CharField(blank=True, max_length=100, null=True)),
                ('django', models.CharField(blank=True, max_length=100, null=True)),
                ('javascript', models.CharField(blank=True, max_length=100, null=True)),
                ('css', models.CharField(blank=True, max_length=100, null=True)),
                ('php', models.CharField(blank=True, max_length=100, null=True)),
                ('laravel', models.CharField(blank=True, max_length=100, null=True)),
                ('react_js', models.CharField(blank=True, max_length=100, null=True)),
                ('python', models.CharField(blank=True, max_length=100, null=True)),
                ('nest_js', models.CharField(blank=True, max_length=100, null=True)),
                ('next_js', models.CharField(blank=True, max_length=100, null=True)),
                ('bootstrap', models.CharField(blank=True, max_length=100, null=True)),
                ('node_js', models.CharField(blank=True, max_length=100, null=True)),
                ('ruby', models.CharField(blank=True, max_length=100, null=True)),
                ('express', models.CharField(blank=True, max_length=100, null=True)),
                ('ajax_js', models.CharField(blank=True, max_length=100, null=True)),
                ('jqury', models.CharField(blank=True, max_length=100, null=True)),
                ('material_ui', models.CharField(blank=True, max_length=100, null=True)),
                ('typescript', models.CharField(blank=True, max_length=100, null=True)),
                ('tailwind_css', models.CharField(blank=True, max_length=100, null=True)),
                ('redux', models.CharField(blank=True, max_length=100, null=True)),
                ('forma', models.ManyToManyField(blank=True, to='Dashbord.form1')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
