# Generated by Django 4.1.3 on 2023-01-04 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashbord', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='form1',
            name='creation_mode',
        ),
        migrations.RemoveField(
            model_name='form2',
            name='forma',
        ),
        migrations.AddField(
            model_name='form3',
            name='finder_code',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='form4',
            name='finder_code',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
