# Generated by Django 4.1.3 on 2024-04-10 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Dashbord', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='form3',
            name='form2',
        ),
    ]
