# Generated by Django 4.1.3 on 2023-01-08 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashbord', '0002_remove_form1_creation_mode_remove_form2_forma_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='form2',
            name='api',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='form3',
            name='published',
            field=models.BooleanField(default=False),
        ),
    ]
