# Generated by Django 4.1.3 on 2023-01-13 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashbord', '0003_form2_api_form3_published'),
    ]

    operations = [
        migrations.CreateModel(
            name='template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_name', models.CharField(max_length=100)),
                ('template_pic', models.ImageField(upload_to='media/dashboard/templatepic')),
                ('discription', models.TextField(max_length=90)),
                ('your_template_demo', models.URLField(blank=True, null=True)),
                ('item_created_date', models.DateTimeField(auto_now=True)),
                ('item_updated_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='form4',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='form4',
            name='your_template',
        ),
        migrations.AddField(
            model_name='form4',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='form4',
            name='published',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='form4',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.RemoveField(
            model_name='form4',
            name='template',
        ),
        migrations.AddField(
            model_name='form4',
            name='template',
            field=models.ManyToManyField(to='Dashbord.template'),
        ),
    ]
